/* DELETE 'accountsDB' database*/
DROP SCHEMA IF EXISTS accountsDB;
/* DELETE USER 'root' AT LOCAL SERVER*/
DROP USER IF EXISTS 'root'@'%';

/* CREATE ''accountsDB' DATABASE */
CREATE SCHEMA accountsDB;
/* CREATE THE USER 'root' AT LOCAL SERVER WITH PASSWORD '' */
CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '';
/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'root' AT LOCAL SERVER*/
GRANT ALL ON accountsDB.* TO 'root'@'%';